version: '3.9'

services:
  
  warehouse-control-antipattern:
    build: .
    container_name: warehouse
    ports:
      - ${SERVICE_PORT}:8081
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    stop_grace_period: 45s
    networks:
      - warehouse-network

  postgres:
    image: postgres:16
    container_name: ${DB_HOST_NAME:-postgres}
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s    
    networks:
      - warehouse-network

volumes:
  postgres-db:

networks:
  warehouse-network:
    driver: bridge